INSERT INTO stanowisko VALUES (1, 'Manager', 1);
INSERT INTO stanowisko VALUES (2, 'Specjalista ds. marketingu', 0);
INSERT INTO stanowisko VALUES (3, 'Analityk biznesowy', 0);
INSERT INTO stanowisko VALUES (4, 'Koordynator projektow', 1);
INSERT INTO stanowisko VALUES (5, 'Pracownik administracyjny', 0);
INSERT INTO stanowisko VALUES (6, 'Inzynier jakosci', 0);
INSERT INTO stanowisko VALUES (7, 'Programista', 0);
INSERT INTO stanowisko VALUES (8, 'Doradca klienta', 0);
INSERT INTO stanowisko VALUES (9, 'Handlowiec', 1);
INSERT INTO stanowisko VALUES (10, 'Asystentka biura', 0);

INSERT INTO wojewodztwo VALUES (1, 'dolnoslaskie');
INSERT INTO wojewodztwo VALUES (2, 'kujawsko-pomorskie');
INSERT INTO wojewodztwo VALUES (3, 'lubelskie');
INSERT INTO wojewodztwo VALUES (4, 'lubuskie');
INSERT INTO wojewodztwo VALUES (5, 'lodzkie');
INSERT INTO wojewodztwo VALUES (6, 'malopolskie');
INSERT INTO wojewodztwo VALUES (7, 'mazowieckie');
INSERT INTO wojewodztwo VALUES (8, 'opolskie');
INSERT INTO wojewodztwo VALUES (9, 'podkarpackie');
INSERT INTO wojewodztwo VALUES (10, 'podlaskie');
INSERT INTO wojewodztwo VALUES (11, 'pomorskie');
INSERT INTO wojewodztwo VALUES (12, 'slaskie');
INSERT INTO wojewodztwo VALUES (13, 'swietokrzyskie');
INSERT INTO wojewodztwo VALUES (14, 'warminsko-mazurskie');
INSERT INTO wojewodztwo VALUES (15, 'wielkopolskie');
INSERT INTO wojewodztwo VALUES (16, 'zachodniopomorskie');

INSERT INTO powiat VALUES (1, 'warszawski', 7);
INSERT INTO powiat VALUES (2, 'piaseczynski', 7);
INSERT INTO powiat VALUES (3, 'otwocki', 7);
INSERT INTO powiat VALUES (4, 'krakowski', 6);
INSERT INTO powiat VALUES (5, 'wielickie', 6);
INSERT INTO powiat VALUES (6, 'gdanski', 11);
INSERT INTO powiat VALUES (7, 'sopot', 11);
INSERT INTO powiat VALUES (8, 'gdynskie', 11);
INSERT INTO powiat VALUES (9, 'wroclawskie', 1);
INSERT INTO powiat VALUES (10, 'legnicki', 1);
INSERT INTO powiat VALUES (11, 'jeleniogorski', 1);
INSERT INTO powiat VALUES (12, 'boleslawieckie', 1);
INSERT INTO powiat VALUES (13, 'poznanskie', 15);
INSERT INTO powiat VALUES (14, 'gnieznienski', 15);
INSERT INTO powiat VALUES (15, 'kaliskie', 15);
INSERT INTO powiat VALUES (16, 'jarocinskie', 15);
INSERT INTO powiat VALUES (17, 'lodzkie', 5);
INSERT INTO powiat VALUES (18, 'pabianickie', 5);
INSERT INTO powiat VALUES (19, 'piotrkowski', 5);
INSERT INTO powiat VALUES (20, 'zgierski', 5);
INSERT INTO powiat VALUES (21, 'katowicki', 12);
INSERT INTO powiat VALUES (22, 'czestochowski', 12);
INSERT INTO powiat VALUES (23, 'rzeszowski', 9);
INSERT INTO powiat VALUES (24, 'przemyski', 9);

INSERT INTO miejscowosc VALUES (1, 1, 'Warszawa', '00-001');
INSERT INTO miejscowosc VALUES (2, 1, 'Piaseczno', '05-500');
INSERT INTO miejscowosc VALUES (3, 1, 'Otwock', '05-400');
INSERT INTO miejscowosc VALUES (3, 2, 'Jozefow', '05-410');
INSERT INTO miejscowosc VALUES (2, 2, 'Konstancin-Jeziorna', '05-510');
INSERT INTO miejscowosc VALUES (4, 1, 'Krakow', '30-001');
INSERT INTO miejscowosc VALUES (5, 1, 'Wieliczka', '32-020');
INSERT INTO miejscowosc VALUES (4, 2, 'Skawina', '32-050');
INSERT INTO miejscowosc VALUES (5, 2, 'Niepolomice', '32-005');
INSERT INTO miejscowosc VALUES (6, 1, 'Gdansk', '80-001');
INSERT INTO miejscowosc VALUES (7, 1, 'Sopot', '81-701');
INSERT INTO miejscowosc VALUES (8, 1, 'Gdynia', '81-001');
INSERT INTO miejscowosc VALUES (9, 1, 'Wroclaw', '50-001');
INSERT INTO miejscowosc VALUES (10, 1, 'Legnica', '59-220');
INSERT INTO miejscowosc VALUES (11, 1, 'Jelenia Gora', '58-500');
INSERT INTO miejscowosc VALUES (12, 1, 'Boleslawiec', '59-700');
INSERT INTO miejscowosc VALUES (13, 1, 'Poznan', '60-001');
INSERT INTO miejscowosc VALUES (14, 1, 'Gniezno', '62-200');
INSERT INTO miejscowosc VALUES (15, 1, 'Kalisz', '62-800');
INSERT INTO miejscowosc VALUES (15, 2, 'Slupia', '63-410');
INSERT INTO miejscowosc VALUES (15, 3, 'Skalmierzyce', '63-430');
INSERT INTO miejscowosc VALUES (16, 1, 'Jarocin', '63-200');
INSERT INTO miejscowosc VALUES (17, 1, 'Łodz', '90-001');
INSERT INTO miejscowosc VALUES (18, 1, 'Pabianice', '95-200');
INSERT INTO miejscowosc VALUES (19, 1, 'Piotrkow Trybunalski', '97-300');
INSERT INTO miejscowosc VALUES (20, 1, 'Zgierz', '95-100');
INSERT INTO miejscowosc VALUES (21, 1, 'Katowice', '40-001');
INSERT INTO miejscowosc VALUES (22, 1, 'Czestochowa', '42-200');
INSERT INTO miejscowosc VALUES (23, 1, 'Rzeszow', '35-001');
INSERT INTO miejscowosc VALUES (24, 1, 'Przemysl', '37-700');
INSERT INTO miejscowosc VALUES (24, 2, 'Dubiecko',	'37-730');
INSERT INTO miejscowosc VALUES (24, 3, 'Bircza', '37-710');
INSERT INTO miejscowosc VALUES (24, 4, 'Krasiczyn', '37-730');

INSERT INTO pracownik VALUES (1, 'Jan', 'Kowalski', 'Kwiatowa', 10, 1, '81082637483', 'jkowalski@firma.com', 0, 2, 7, 1, 1);
INSERT INTO pracownik VALUES (2, 'Anna', 'Nowak', 'Sloneczna', 15, 2, '89032976129', 'anowak@firma.com', 0, 5, 6, 4, 1);
INSERT INTO pracownik VALUES (3, 'Piotr', 'Wojcik', 'Krotka', 20, 3, '85102798375', 'pwojcik@firma.com', 1, 8, 11, 6, 1);
INSERT INTO pracownik VALUES (4, 'Maria', 'Kaczmarek', 'Lipowa', 30, 4, '92070267823', 'mkaczmarek@firma.com', 0, 1, 11, 7, 1);
INSERT INTO pracownik VALUES (10, 'Katarzyna', 'Kaminska', 'Morska', 90, 10, '80042045871', 'kkaminska@firma.com', 0, 6, 11, 7, 1);
INSERT INTO pracownik (id_pracownika, imie, nazwisko, ulica, nr_domu, pesel, email, id_stanowiska, id_wojewodztwa, id_powiatu, id_miejscowosci) VALUES (5, 'Tomasz', 'Lewandowski', 'Kosciuszki', 40, '85081513243', 'tlewandowski@firma.com', 3, 9, 24, 4);
INSERT INTO pracownik (id_pracownika, imie, nazwisko, ulica, nr_domu, pesel, email, id_stanowiska, id_wojewodztwa, id_powiatu, id_miejscowosci) VALUES (6, 'Agnieszka', 'Dąbrowska', 'Swietokrzyska', 50, '81030484689', 'adabrowska@firma.com', 10, 9, 24, 2);
INSERT INTO pracownik (id_pracownika, imie, nazwisko, ulica, nr_domu, pesel, email, id_stanowiska, id_wojewodztwa, id_powiatu, id_miejscowosci) VALUES (7, 'Marcin', 'Zielinski', 'Warszawska', 60, '91070254375', 'mzielinski@firma.com', 4, 9, 23, 1);
INSERT INTO pracownik (id_pracownika, imie, nazwisko, ulica, nr_domu, pesel, email, id_stanowiska, id_wojewodztwa, id_powiatu, id_miejscowosci) VALUES (8, 'Magdalena', 'Szymańska', 'Mickiewicza', 70, '90071525837', 'mszymanska@firma.com', 9, 15, 15, 3);
INSERT INTO pracownik (id_pracownika, imie, nazwisko, ulica, nr_domu, pesel, email, id_stanowiska, id_wojewodztwa, id_powiatu, id_miejscowosci) VALUES (9, 'Michal', 'Wozniak', 'Krzywa', 80, '79052783265', 'mwozniak@firma.com', 7, 15, 15, 2);
INSERT INTO pracownik (id_pracownika, imie, nazwisko, ulica, nr_domu, pesel, email, id_stanowiska, id_wojewodztwa, id_powiatu, id_miejscowosci) VALUES (11, 'Pawel', 'Kozlowski', 'Koscielna', 11, '88031054733', 'pkozlowski@firma.com', 2, 15, 15, 3);
INSERT INTO pracownik (id_pracownika, imie, nazwisko, ulica, nr_domu, pesel, email, id_stanowiska, id_wojewodztwa, id_powiatu, id_miejscowosci) VALUES (12, 'Beata', 'Kowalczyk', 'Szkolna', 12, '85070684629', 'bkowalczyk@firma.com', 5, 15, 15, 1);
