CREATE OR REPLACE TRIGGER benefit_t_trigger
AFTER UPDATE OR INSERT OR DELETE ON BENEFIT_T
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  DBMS_MVIEW.REFRESH('BENEFIT');
  DBMS_MVIEW.REFRESH('INNY_BENEFIT');
  DBMS_MVIEW.REFRESH('PREMIA');
  DBMS_MVIEW.REFRESH('SAMOCHOD');
  DBMS_MVIEW.REFRESH('URZADZENIE_ELEKTRONICZNE');
END;
/
CREATE OR REPLACE TRIGGER inny_benefit_t_trigger
AFTER UPDATE OR INSERT OR DELETE ON INNY_BENEFIT_T
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;BEGIN
  DBMS_MVIEW.REFRESH('BENEFIT');
  DBMS_MVIEW.REFRESH('INNY_BENEFIT');
END;
/
CREATE OR REPLACE TRIGGER premia_t_trigger
AFTER UPDATE OR INSERT OR DELETE ON PREMIA_T
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;BEGIN
  DBMS_MVIEW.REFRESH('BENEFIT');
  DBMS_MVIEW.REFRESH('PREMIA');
END;
/
CREATE OR REPLACE TRIGGER samochod_t_trigger
AFTER UPDATE OR INSERT OR DELETE ON SAMOCHOD_T
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;BEGIN
  DBMS_MVIEW.REFRESH('BENEFIT');
  DBMS_MVIEW.REFRESH('SAMOCHOD');
END;
/
CREATE OR REPLACE TRIGGER urzadzenie_t_trigger
AFTER UPDATE OR INSERT OR DELETE ON URZADZENIE_ELEKTRONICZNE_T
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  DBMS_MVIEW.REFRESH('BENEFIT');
  DBMS_MVIEW.REFRESH('URZADZENIE_ELEKTRONICZNE');
END;
/
CREATE OR REPLACE TRIGGER wniosek_t_trigger
AFTER UPDATE OR INSERT OR DELETE ON WNIOSEK_T
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;BEGIN
  DBMS_MVIEW.REFRESH('WNIOSEK');
  DBMS_MVIEW.REFRESH('WNIOSEK_BONUS');
  DBMS_MVIEW.REFRESH('WNIOSEK_INNY');
  DBMS_MVIEW.REFRESH('WNIOSEK_URLOP');
END;
/
CREATE OR REPLACE TRIGGER wniosek_bonus_t_trigger
AFTER UPDATE OR INSERT OR DELETE ON WNIOSEK_BONUS_T
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;BEGIN
  DBMS_MVIEW.REFRESH('WNIOSEK');
  DBMS_MVIEW.REFRESH('WNIOSEK_BONUS');
END;
/
CREATE OR REPLACE TRIGGER wniosek_inny_t_trigger
AFTER UPDATE OR INSERT OR DELETE ON WNIOSEK_INNY_T
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;BEGIN
  DBMS_MVIEW.REFRESH('WNIOSEK');
  DBMS_MVIEW.REFRESH('WNIOSEK_INNY');
END;
/
CREATE OR REPLACE TRIGGER wniosek_urlop_t_trigger
AFTER UPDATE OR INSERT OR DELETE ON WNIOSEK_URLOP_T
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;BEGIN
  DBMS_MVIEW.REFRESH('WNIOSEK');
  DBMS_MVIEW.REFRESH('WNIOSEK_URLOP');
END;
/
commit;