#--------- TABLE NAMES ----------#

TABLE_NAME_EMPLOYEES            = "benefit_t"
TABLE_NAME_CERTIFICATE          = "certyfikat"
TABLE_NAME_CERTIFICATE_EMPLOYEE = "certyfikat_pracownik"
TABLE_NAME_CONTACT_DATA         = "dane_kontaktowe"
TABLE_NAME_LOGIN_DATA           = "dane_logowania"
TABLE_NAME_OTHER_BENEFIT        = "inny_benefit_t"
TABLE_NAME_TOWN                 = "miejscowosc"
TABLE_NAME_COUNTY               = "powiat"
TABLE_NAME_EMPLOYEE             = "pracownik"
TABLE_NAME_EMPLOYEE_LOGIN       = "pracownik_logowanie"
TABLE_NAME_BONUS                = "premia_t"
TABLE_NAME_CAR                  = "samochod_t"
TABLE_NAME_POSITION             = "stanowisko"
TABLE_NAME_CONTRACT             = "umowa"
TABLE_NAME_ELECTRONICAL_DEVICE  = "urzadzenie_elektroniczne_t"
TABLE_NAME_APPLICATION_BONUS    = "wniosek_bonus_t"
TABLE_NAME_APPLICATION_OTHER    = "wniosek_inny_t"
TABLE_NAME_APPLICATION          = "wniosek_t"
TABLE_NAME_APPLICATION_HOLIDAY  = "wniosek_urlop_t"
TABLE_NAME_PROVINCE             = "wojewodztwo"
TABLE_NAME_TEAM                 = "zespol"
TABLE_NAME_TEAMTEAM_EMPLOYEE    = "zespol_pracownik"